<?php

return [
    'enabled' => (bool) env('LEGACY_MIGRATION_ENABLED', false),
    'schema' => env('LEGACY_MIGRATION_SCHEMA', 'haidang-legacy-content.v1'),
    'token_hash' => env('LEGACY_MIGRATION_TOKEN_HASH'),
    'disk' => env('LEGACY_MIGRATION_DISK', 'local'),
    'max_body_bytes' => (int) env('LEGACY_MIGRATION_MAX_BODY_BYTES', 12 * 1024 * 1024),
    'max_urls_per_chunk' => (int) env('LEGACY_MIGRATION_MAX_URLS_PER_CHUNK', 500),
    'max_objects_per_chunk' => (int) env('LEGACY_MIGRATION_MAX_OBJECTS_PER_CHUNK', 5000),
    'source_timezone' => env('LEGACY_MIGRATION_SOURCE_TIMEZONE', 'Asia/Bangkok'),
    'queue' => env('LEGACY_MIGRATION_QUEUE', 'default'),
    'recovery' => [
        'stale_after_seconds' => (int) env('LEGACY_MIGRATION_RECOVERY_STALE_AFTER_SECONDS', 300),
    ],
    'media' => [
        'skip_failed_images' => filter_var(env('LEGACY_MIGRATION_MEDIA_SKIP_FAILED_IMAGES', true), FILTER_VALIDATE_BOOL),
        'max_download_seconds_per_object' => (int) env('LEGACY_MIGRATION_MEDIA_MAX_DOWNLOAD_SECONDS_PER_OBJECT', 40),
        'ca_bundle' => env('LEGACY_MIGRATION_MEDIA_CA_BUNDLE', ''),
        'source_url_overrides' => json_decode((string) env('LEGACY_MIGRATION_MEDIA_SOURCE_URL_OVERRIDES', '{}'), true) ?: [],
        'allow_any_public_host' => filter_var(
            env('LEGACY_MIGRATION_MEDIA_ALLOW_ANY_PUBLIC_HOST', true),
            FILTER_VALIDATE_BOOL,
        ),
        'allowed_hosts' => array_values(array_filter(array_map(
            'trim',
            explode(',', (string) env('LEGACY_MIGRATION_MEDIA_ALLOWED_HOSTS', 'tour.org.vn,haidangtravel.com,www.haidangtravel.com')),
        ))),
        'download_source_remap_from_hosts' => array_values(array_filter(array_map(
            'trim',
            explode(',', (string) env('LEGACY_MIGRATION_MEDIA_REMAP_FROM_HOSTS', 'haidangtravel.com,www.haidangtravel.com')),
        ))),
        'download_source_remap_to_host' => env('LEGACY_MIGRATION_MEDIA_REMAP_TO_HOST', 'tour.org.vn'),
        'max_images_per_object' => (int) env('LEGACY_MIGRATION_MEDIA_MAX_IMAGES_PER_OBJECT', 100),
        'max_embedded_image_bytes' => (int) env('LEGACY_MIGRATION_MEDIA_MAX_EMBEDDED_IMAGE_BYTES', 5 * 1024 * 1024),
        'max_embedded_total_bytes' => (int) env('LEGACY_MIGRATION_MEDIA_MAX_EMBEDDED_TOTAL_BYTES', 10 * 1024 * 1024),
        'max_embedded_pixels' => (int) env('LEGACY_MIGRATION_MEDIA_MAX_EMBEDDED_PIXELS', 24_000_000),
        'max_remote_pixels' => (int) env('LEGACY_MIGRATION_MEDIA_MAX_REMOTE_PIXELS', 24_000_000),
    ],
    'allowed_source_systems' => array_values(array_filter(array_map(
        'trim',
        explode(',', (string) env('LEGACY_MIGRATION_ALLOWED_SOURCES', 'haidangtravel_legacy')),
    ))),
    'allowed_source_ips' => array_values(array_filter(array_map(
        'trim',
        explode(',', (string) env('LEGACY_MIGRATION_ALLOWED_IPS', '')),
    ))),
    'supported_object_types' => [
        'tour',
        'subject_tour',
        'destination',
        'region',
        'source_point',
        'tour_detail_day',
        'tour_start_date',
        'sight_point',
        'tour_review',
        'tour_rating_summary',
        'blog',
        'subject_blog',
        'public_author',
        'blog_rating_summary',
        'destination_rating_summary',
        'page',
        'config',
        'banner',
        'redirect',
        'homepage',
        'tour_listing',
        'blog_listing',
        'static_page',
    ],
    'supported_route_kinds' => [
        'homepage',
        'tour_listing',
        'static_page',
        'blog_category',
        'blog_detail',
        'blog_listing',
        'destination_detail',
        'tour_category',
        'tour_detail',
        'page_detail',
        'legacy_destination_landing',
        'legacy_blog_detail',
        'unresolved',
    ],
];
