<?php

return [
    'queue' => env('SEO_AI_QUEUE', 'seo'),
    'publish_mode' => env('SEO_AI_PUBLISH_MODE', 'manual_review'),
    'business_name' => env('SEO_AI_BUSINESS_NAME', 'Hải Đăng Travel'),
    'contact_phone' => env('SEO_AI_CONTACT_PHONE'),
    'contact_email' => env('SEO_AI_CONTACT_EMAIL'),
    'address_locality' => env('SEO_AI_ADDRESS_LOCALITY'),
    'address_region' => env('SEO_AI_ADDRESS_REGION'),
    'address_country' => env('SEO_AI_ADDRESS_COUNTRY', 'VN'),
    'default_model' => env('SEO_AI_MODEL', 'gpt-5'),
    'base_url' => env('OPENAI_BASE_URL', 'https://api.openai.com/v1'),
    'quality_gates' => [
        'service_word_count_min' => 900,
        'service_category_word_count_min' => 650,
        'blog_word_count_min' => 1200,
        'tour_category_word_count_min' => 650,
        'destination_word_count_min' => 850,
        'region_word_count_min' => 750,
        'country_word_count_min' => 750,
        'project_word_count_min' => 800,
        'contact_word_count_min' => 300,
        'location_landing_word_count_min' => 700,
        'meta_title_min' => 45,
        'meta_title_max' => 60,
        'meta_description_min' => 120,
        'meta_description_max' => 160,
        'require_meta_title' => true,
        'require_meta_description' => true,
        'require_schema' => true,
        'require_h1' => true,
        'min_internal_links' => 1,
    ],
];
